
[window]
decorations = "Full"
padding = 10
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
